apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: <your-aws-account-id>.dkr.ecr.<your-region>.amazonaws.com/my-node-app-repo:latest
        ports:
        - containerPort: 8080
